services:
  frontend:
    image: kondsrav/stoat-frontend-prod:stoat
    ports:
      - "3000:80"
    environment:
      - VITE_API_URL=https://stoat-dev.zasperhub.com/api
      - VITE_WS_URL=wss://stoat-dev.zasperhub.com/ws
      - VITE_MEDIA_URL=https://stoat-dev.zasperhub.com/autumn
      - VITE_PROXY_URL=https://stoat-dev.zasperhub.com/january
      - VITE_HCAPTCHA_SITEKEY=${VITE_HCAPTCHA_SITEKEY:-}
      - VITE_SENTRY_DSN=${VITE_SENTRY_DSN:-}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - stoat-network-stable

networks:
  stoat-network-stable:
    external: true

